# Generated by Django 5.2.7 on 2025-10-28 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employe',
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('fichier_pdf', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('envoyee', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='fiche_paie.employe')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'db_table': 'fiche_paie',
            },
        ),
        migrations.CreateModel(
            name='EnvoiEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois_email', to='fiche_paie.fichepaie')),
            ],
            options={
                'verbose_name': "Envoi d'email",
                'verbose_name_plural': "Envois d'emails",
                'db_table': 'envoi_email',
            },
        ),
    ]
